services:
  - type: web
    name: claudable-api
    env: python
    buildCommand: |
      # Install Node.js 20
      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      sudo apt-get install -y nodejs
      
      # Set up Python environment
      python3 -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r apps/api/requirements.txt
      
      # Install AI Agent CLI tools
      export PATH="/usr/bin:$PATH"
      npm install -g @anthropic-ai/claude-code
      npm install -g @openai/codex
      npm install -g @google/gemini-cli
      npm install -g @qwen-code/qwen-code
      
      # Install Cursor Agent CLI
      curl -fsSL https://cursor.com/install | bash
      export PATH="$HOME/.local/bin:$PATH"
      
      # Initialize database
      cd apps/api
      python -c "
      from app.db.session import engine
      from app.db.base import Base
      Base.metadata.create_all(bind=engine)
      print('Database initialized')
      "
    startCommand: |
      export PATH="$HOME/.local/bin:/usr/bin:$PATH"
      source .venv/bin/activate
      cd apps/api
      python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///data/cc.db
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: RENDER
        value: true
      - key: NODE_PATH
        value: /usr/bin/node
      - key: PATH
        value: /home/render/.local/bin:/usr/bin:/usr/local/bin
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1

  - type: web
    name: claudable-web
    env: static
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: apps/web/.next
    routes:
      - type: rewrite
        source: /api/*
        destination: https://claudable-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: https://claudable-api.onrender.com
      - key: NEXT_PUBLIC_WS_BASE
        value: wss://claudable-api.onrender.com
